# Generated by Django 4.0.4 on 2023-09-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='location_photo_link',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
