# Generated by Django 4.0.1 on 2022-03-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0005_delete_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('iscte', 'Iscte'), ('portugal', 'Portugal'), ('world', 'World')], default='iscte', max_length=12)),
                ('topics', models.ManyToManyField(related_name='events', to='topics.Topic')),
            ],
        ),
    ]
