# Generated by Django 4.0.4 on 2022-11-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_title'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date'], name='events_even_date_5e8e1c_idx'),
        ),
    ]
