# Generated by Django 4.0.4 on 2023-01-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_events_even_date_5e8e1c_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=600),
        ),
    ]
