# Generated by Django 4.0.1 on 2022-02-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='description',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='topic',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='topicaccess',
            name='when',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('document', 'Document'), ('web_page', 'Web page'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('social_media', 'Social media')], max_length=12)),
                ('topics', models.ManyToManyField(to='topics.Topic')),
            ],
        ),
    ]
