# Generated by Django 4.0.1 on 2022-02-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_rename_description_topic_title_alter_topic_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicaccess',
            name='is_scan',
        ),
        migrations.AlterField(
            model_name='content',
            name='topics',
            field=models.ManyToManyField(related_name='content', to='topics.Topic'),
        ),
    ]
