# Generated by Django 4.0.1 on 2022-03-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_remove_topicaccess_is_scan_alter_content_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='scope',
            field=models.CharField(choices=[('iscte', 'Iscte'), ('portugal', 'Portugal'), ('world', 'World')], default='iscte', max_length=12),
        ),
    ]
