# Generated by Django 4.0.1 on 2022-03-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0005_delete_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.CharField(blank=True, max_length=100)),
                ('scope', models.CharField(choices=[('iscte', 'Iscte'), ('portugal', 'Portugal'), ('world', 'World')], default='iscte', max_length=12)),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('document', 'Document'), ('web_page', 'Web page'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('social_media', 'Social media')], max_length=12)),
                ('topics', models.ManyToManyField(related_name='content', to='topics.Topic')),
            ],
        ),
    ]
