# Generated by Django 4.0.4 on 2022-08-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('document', 'Document'), ('web_page', 'Web page'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('social_media', 'Social media')], max_length=12)),
                ('topics', models.ManyToManyField(related_name='content', to='topics.topic')),
            ],
        ),
    ]
