# Generated by Django 4.0.1 on 2022-03-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='scope',
        ),
    ]
