# Generated by Django 4.0.4 on 2022-09-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_content_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='link',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
