# Generated by Django 4.0.4 on 2022-11-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_content_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
