# Generated by Django 4.0.4 on 2022-11-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_content_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
