# Generated by Django 4.0.1 on 2022-02-01 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cycle', models.CharField(choices=[(' BSc', "Bachelor's"), ('MSc', "Master's"), ('PhD', 'Doctorate')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('percent_correct', models.DecimalField(decimal_places=2, max_digits=3)),
                ('topics_required', models.IntegerField()),
                ('trials_allowed', models.IntegerField()),
                ('max_points_quiz', models.IntegerField()),
                ('max_time_per_question', models.IntegerField()),
                ('num_single_questions', models.IntegerField()),
                ('num_multiple_questions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('st', 'Student'), ('prof', 'Professor'), ('researcher', 'Researcher'), ('staff', 'Staff')], max_length=10)),
                ('level', models.IntegerField(default=1)),
                ('points', models.IntegerField(default=0)),
                ('affiliation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.affiliation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
