# Generated by Django 4.0.4 on 2022-09-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='users_profi_num_spo_04c653_idx',
        ),
        migrations.RemoveField(
            model_name='level',
            name='level',
        ),
        migrations.RemoveField(
            model_name='level',
            name='max_points_quiz',
        ),
        migrations.RemoveField(
            model_name='level',
            name='max_time_per_question',
        ),
        migrations.RemoveField(
            model_name='level',
            name='max_topics',
        ),
        migrations.RemoveField(
            model_name='level',
            name='min_topics',
        ),
        migrations.RemoveField(
            model_name='level',
            name='num_multiple_questions',
        ),
        migrations.RemoveField(
            model_name='level',
            name='num_single_questions',
        ),
        migrations.RemoveField(
            model_name='level',
            name='percent_correct',
        ),
        migrations.RemoveField(
            model_name='level',
            name='trials_allowed',
        ),
        migrations.AddField(
            model_name='level',
            name='num_topics',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='question_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
