# Generated by Django 4.0.1 on 2022-02-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='topics_required',
            new_name='max_topics',
        ),
        migrations.AddField(
            model_name='level',
            name='min_topics',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='cycle',
            field=models.CharField(choices=[('bsc', "Bachelor's"), ('msc', "Master's"), ('phd', 'Doctorate')], max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('student', 'Student'), ('prof', 'Professor'), ('researcher', 'Researcher'), ('staff', 'Staff')], max_length=10),
        ),
    ]
