# Generated by Django 4.0.4 on 2022-09-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_users_profi_num_spo_04c653_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliation',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='subtype',
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='type',
        ),
        migrations.AddField(
            model_name='affiliation',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
