# Generated by Django 4.0.1 on 2022-02-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_questions_alter_question_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
