# Generated by Django 4.0.4 on 2023-04-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
    ]
