# Generated by Django 4.2 on 2023-04-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_answer_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_num_trials',
            field=models.IntegerField(default=3),
        ),
    ]
